return Def.ActorFrame{
	LoadActor("arrow")..{
	InitCommand=function(self)
		self:x(SCREEN_LEFT+64):y(SCREEN_CENTER_Y)
	end;
	OnCommand=function(self)
		self:addx(-200):decelerate(0.5):addx(200)
	end;
	MenuLeftP1MessageCommand=function(self)
		self:playcommand("Blink")
	end;
	MenuLeftP2MessageCommand=function(self)
		self:playcommand("Blink")
	end;
	BlinkCommand=function(self)
		self:finishtweening():zoom(1.2):glow(1,1,1,1):linear(0.2):glow(1,1,1,0):zoom(1)
	end;
	MadeChoiceP1MessageCommand=function(self)
		self:playcommand("GoOff")
	end;
	MadeChoiceP2MessageCommand=function(self)
		self:playcommand("GoOff")
	end;
	OffCommand=function(self)
		self:accelerate(0.5):addx(-200)
	end;
	},
	LoadActor("arrow")..{
	InitCommand=function(self)
		self:x(SCREEN_RIGHT-64):y(SCREEN_CENTER_Y):rotationz(180)
	end;
	OnCommand=function(self)
		self:addx(-200):decelerate(0.5):addx(200)
	end;
	MenuRightP1MessageCommand=function(self)
		self:playcommand("Blink")
	end;
	MenuRightP2MessageCommand=function(self)
		self:playcommand("Blink")
	end;
	BlinkCommand=function(self)
		self:finishtweening():zoom(1.2):glow(1,1,1,1):linear(0.2):glow(1,1,1,0):zoom(1)
	end;
	MadeChoiceP1MessageCommand=function(self)
		self:playcommand("GoOff")
	end;
	MadeChoiceP2MessageCommand=function(self)
		self:playcommand("GoOff")
	end;
	OffCommand=function(self)
		self:accelerate(0.5):addx(200)
	end;
	},
}