return Def.ActorFrame{
	Def.ActorScroller {
	SecondsPerItem = 0.28,
	NumItemsToDraw = 21,
	TransformFunction = function( self, offset, itemIndex, numItems) self:x(SCREEN_CENTER_X) self:y(offset*24) end,
	OnCommand=cmd(scrollwithpadding,6,9),

		Def.BitmapText{ Text="IN THE GROOVE TEAM", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#D57676");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="PRODUCER", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Jason Asbahr", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="PROGRAMMING", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Glenn Maynard", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Chris Danford", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="SOUND", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Kyle Ward", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="STEP ARTISTS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Kyle Ward", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Chris Foy", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Matthew Emirzian", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Ryan McKanna", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Matt Puls", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Jonas Casarino", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Christopher Emirzian", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="THEME GRAPHICS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Heather Dority", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Ryan McKanna", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Chris Danford", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Glenn Maynard", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="SONG/COURSE GRAPHICS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Ryan McKanna", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Matt Puls", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Heather Dority", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="BUSINESS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Jason Asbahr", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="John Cooney", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="SYSADMIN", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Travis B. Hartwell", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="HARDWARE", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="John Cooney", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="ILLUSTRATOR", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Beth Schultz", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="TEST LOCATIONS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="8 on the Break - Dunellen, NJ", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="SPECIAL THANKS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Kevin McKanna", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Jennifer Putzier", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Rhea Dysangco", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Cinnamon Cooney", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Lee Search", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Gina “Lou” Hall", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Aaron Shafer", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Kristy Bowden", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Koley Porter", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Audrey Maker", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Andrew Locko", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="RED OCTANE SOFTWARE", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="John Tam", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Ted Lange", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Mark Johnson", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Raul Renteria", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Jordan Dodge", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Daniyel Garcia", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="STEPMANIA PROGRAMMERS", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Frieza", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Peter “Dro Kulix” May", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Jared “nmspaz” Roberts", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Brendan “binarys” Walker", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Lance “Neovanglist” Gilbert", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Michel Donais", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Ben “Mantis” Nordstrom", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Chris “Parasyte” Gomez", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Michael “dirkthedaring” Patterson", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Sauleil “angedelamort” Lamarre", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Edwin Evans", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Brian “Bork” Bugh", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Joel “Elvis314” Maher", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Garth “Kefabi” Smith", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Pkillah", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Robert Kemmetmueller", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Ben “Shabach” Andersen", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Will “SlinkyWizard” Valladao", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="TheChip", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="David “WarriorBob” H", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Mike Waltson", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Kevin “Miryokuteki” Slaughter", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Thad “Coderjoe” Ward", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Steve Checkoway", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="Sean Burke", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="XPort", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="IN THANKS AND MEMORY OF", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#76B1D5");ztest,1); },
		Def.BitmapText{ Text="Steve Blattspieler", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
		Def.BitmapText{ Text="", Font="_eurostile normal", OnCommand=cmd(zoom,0.7;diffuse,color("#FFFFFF");ztest,1); },
	},
}
