return Def.ActorFrame{
    StartTransitioningCommand=function(self)
        self:sleep(1)
    end,
    Def.Quad{
        InitCommand=function(self)
            self:FullScreen():diffuse(Color.Black)
            :diffusealpha(0)
        end,
        StartTransitioningCommand=function(self)
            self:linear(0.5):diffusealpha(1)
        end
    },
    Def.Sprite{
        Texture=THEME:GetPathB("","_flash"),
        InitCommand=function(self)
            self:Center():blend("add"):zoom(0):diffusealpha(0)
            :rotationz(-20)
        end,
        StartTransitioningCommand=function(self)
            self:linear(0.5):zoom(10):diffusealpha(1)
            :rotationz(40)
        end
    },
    Def.Sprite{
        Texture=THEME:GetPathB("","_flash"),
        InitCommand=function(self)
            self:Center():blend("add"):zoom(0):diffusealpha(0)
            :rotationz(20)
        end,
        StartTransitioningCommand=function(self)
            self:linear(0.5):zoom(10):diffusealpha(1)
            :rotationz(-40)
        end
    },

    Def.Sound{
		File=THEME:GetPathS("Common","coin"),
		StartTransitioningCommand=function(self)
            SOUND:StopMusic()
			self:play()
		end
	}
}